#!/usr/bin/env bash

set -o allexport
source .env
set +o allexport

poetry run \ 
  gunicorn mars_tiler:app \
    --bind 0.0.0.0:$MARS_TILER_PORT \
    --workers 8 \
    --worker-class uvicorn.workers.UvicornWorker
